import { BaseModel } from '../../_base/crud';
import {RegUserMoleson} from './RegData.model';
import {AccessLevel} from './accsessLevel.model';

export class User extends BaseModel {
	INN: string;
	accessLevel: AccessLevel;
	SNILS: string;
	amountOfPurchases: number;
	money: number;
	birthday: string;
	citizenship: string;
	dateCreate: number;
	dateIssued: string;
	departmentCode: string;
	email: string;
	password: string;
	expectsWithdrawal: number;
	fullName: string;
	fullname: string;
	regDate: RegUserMoleson;
	gender: string;
	isInstallmentPlan: boolean;
	isVerified: boolean;
	isVerifiedMail: boolean;
	issued: string;
	level: number;
	passportId: string;
	passportImg: string;
	registrationAddress: string;
	shoppingInStructure: number;
	urlMailConfirmation: string;
	username: string;
	pic: string;
	avatar: string;
	passport: string;
	_id: string;
	accessToken: string;
	balance: number;
	picture: any;
	clear(): void {
		this.accessLevel = new AccessLevel();
		this.regDate = new RegUserMoleson();
		this.INN = '';
		this.SNILS = '';
		this.amountOfPurchases = 0;
		this.money = 0;
		this.pic = './assets/media/users/default.jpg';
		this.birthday = '';
		this.citizenship = '';
		this.dateCreate = 0;
		this.dateIssued = '';
		this.departmentCode = '';
		this.email = '';
		this.expectsWithdrawal = 0;
		this.fullName = '';
		this.fullname = '';
		this.gender = '';
		this.isInstallmentPlan = false;
		this.isVerified = false;
		this.isVerifiedMail = false;
		this.passportId = '';
		this.passport = '';
		this.avatar = '';
		this.password = '';
		this.level = 0;
		this.accessToken = '';
		this.issued = '';
		this.passportImg = '';
		this.registrationAddress = '';
		this.shoppingInStructure = 0;
		this.urlMailConfirmation = '';
		this.username = '';
		this._id = '';
	}
}
